description: "Visdown: Visualisation using Markdown"
author: amitkaps

twitter:
  username: amitkaps

url: http://visdown.amitkaps.com
permalink: pretty
port: 4001

gems:
  - jekyll-seo-tag

collections:
  examples:
    output: True

  pages:
    output: True

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      image: /img/visdown.png
